using System;
using System.Collections.Generic;

namespace YouTubeDownloader.Models
{
    // This class holds information about a YouTube video
    // I learned about classes from a C# tutorial
    public class VideoInfo
    {
        public string Title { get; set; } = string.Empty;
        public int Duration { get; set; }
        public string Uploader { get; set; } = string.Empty;
        public string? ThumbnailUrl { get; set; }
        
        public List<ThumbnailInfo> Thumbnails { get; set; } = new();
        public List<SubtitleInfo> Subtitles { get; set; } = new();
    }

    public class ThumbnailInfo
    {
        public string Url { get; set; } = string.Empty;
        public int Width { get; set; }
        public int Height { get; set; }
        public string Resolution => $"{Width}x{Height}";
    }

    public class SubtitleInfo
    {
        public string LanguageCode { get; set; } = string.Empty;
        public string Name { get; set; } = string.Empty;
        public bool IsAutoGenerated { get; set; }
        public string DisplayName => IsAutoGenerated ? $"{Name} (Auto)" : Name;
    }
}
